### ISSUE TITLE
Instructions in code are not correct.

### ISSUE THREAD

**Issue by Dave-Lowndes** [microsoft/ConcordExtensibilitySamples#105]
Comment in https://github.com/microsoft/ConcordExtensibilitySamples/blob/main/CppCustomVisualizer/TargetApp/TargetApp.cpp says

" __debugbreak(); // program will stop here. Evaluate 'creationTime' and 'pPointerTest' in the locals or watch window."

However, there's no pPointerTest currently.

Similarly, but perhaps more importantly, in https://github.com/microsoft/ConcordExtensibilitySamples/blob/main/CppCustomVisualizer2/TargetApp/TargetApp.cpp the same _debugbreak is there, but the source seems unrelated.

**Comment by gregg-miskelly** [comment]
Sorry @calgagi didn't mean to assign this to you.
