### ISSUE TITLE
.Net 8 problems

### ISSUE THREAD

**Issue by netcompany-runeviumsondergaard** [microsoft/ConcordExtensibilitySamples#112]
Hello there!
I have been using the ability to attach the debugger in a running Docker container, and I have worked like a charm.
However, now after we have updated to .Net 8 the debugger just dies when I try to attach, is this a common known bug? It's kind of a showstopper :) 
I can't really give any error codes  from Visual Studio, I just says "The debug adapter exited unexpectedly."
In Visual Studio code it just seems like it attaches, and then it drops. 
Are there soon a new version coming? Or am I the only one with this problem?

- Rune

**Comment by gregg-miskelly** [comment]
This repo is really just for folks trying to extend the debugger. I ported your issue to https://github.com/dotnet/vscode-csharp/issues/6828 as a better place.
