### ISSUE TITLE
Breakpoints set before module is created get lost

### ISSUE THREAD

**Issue by d11mphillips** [microsoft/ConcordExtensibilitySamples#117]
If a breakpoint is set before the module is created, I don't receive any IDkmSymbolDocumentCollectionQuery.FindDocuments() or IDkmRuntimeMonitorBreakpointHandler.EnableRuntimeBreakpoint() callbacks unless the breakpoint is removed and reinstated.

During module creation this exception is raised:

```
OnException: filter exception.
System.NotImplementedException: The method or operation is not implemented.
   at XapiExceptionProcessing.ThrowHR(Int32 code)
   at Microsoft.VisualStudio.Debugger.Symbols.DkmModule.FindDocuments(DkmWorkList WorkList, DkmSourceFileId SourceFileId, DkmCompletionRoutine`1 CompletionRoutine)
   at VSDebugEngine.BreakpointManager.BMDocument.BeginResolveInModule(DkmWorkList workList, DkmModule module, Nullable`1 span)
   at VSDebugEngine.BreakpointManager.BMFileLineBreakpointCollection.OnModuleCreate(BMEventHandlerContext eventHandlerContext, DkmModule module)
   at VSDebugEngine.BreakpointManager.EntryPoint.Microsoft.VisualStudio.Debugger.ComponentInterfaces.IDkmModuleCreateNotification.OnModuleCreate(DkmModule module, DkmEventDescriptorS eventDescriptor)
   at Microsoft.VisualStudio.Debugger.EntryPoint.IDkmModuleCreateNotification_OnModuleCreate(IntPtr pvClassInfo, IntPtr Module, IntPtr EventDescriptor)The thread 0x6e28 has exited with code 0 (0x0).
```

but the exception message doesn't hint at what, exactly, is not implemented. Any idea if it's a missing interface I need to implement?

Everything appears to work fine if I wait until the module has been created before setting breakpoints. They even get queued up in between creating the module and the module instance, and fired on the instance creation, which is good.

Thanks in advance!

**Comment by gregg-miskelly** [comment]
Based on that stack, what is probably happening is that the dispatcher can't find an implementation of IDkmSymbolDocumentSpanQuery that it is allowed to call. Are you implementing that interface? If so, what is the component level of your component that implements it? 

Also, are you creating your module instance with the associated DkmModule initially set? Or calling DkmModuleInstance.SetModule?

**Comment by d11mphillips** [comment]
Yes I implement IDkmSymbolDocumentSpanQuery on the local component, level 9995000. My remote component is 40500 for comparison. I think this is implemented correctly because it gets hit if I set breakpoints after the module and module instance creation, and symbol lookup/breakpoint creation works fine from there on.

The exception is raised during DkmModule.Create() so the damage is already done by the time we hit DkmModuleInstance.Create(). I am passing the module to the DkmModuleInstance constructor, but I've also just given DkmModuleInstance.SetModule() a try to see if it reloads symbols after the fact, but there's no change in behaviour.

I've just noticed that even if I don't set any breakpoints before module creation, then DkmModule.Create() still raises the exception, so I'm not sure what document it would be trying to query since without any breakpoints it wouldn't be aware of the existence of any documents. Perhaps this points to a red herring, and my problem is nothing to do with that exception but simply that I'm missing a call to something which looks up pre-existing breakpoints after module/instance creation?

**Comment by gregg-miskelly** [comment]
I believe if you look at [logging](https://github.com/Microsoft/ConcordExtensibilitySamples/wiki/Getting-troubleshooting-logs) for `IDkmSymbolDocumentSpanQuery` we can double check there isn't some other problem, but I am almost certain the problem is your component level of your symbol provider (component which implements `IDkmSymbolDocumentSpanQuery`). The issue is that the breakpoint manager is at level 9,994,000, so it will see the module create before your symbol provider, and the dispatcher doesn't want to allow calls to your component before it has had a chance to process the create event.

**Comment by d11mphillips** [comment]
Yes, that was it! Thank you for the help, all working now.

For future releases, please could any uses of System.NotImplementedException describe the thing that is not implemented?

Cheers!
