### ISSUE TITLE
Exception information "view details"

### ISSUE THREAD

**Issue by carlokok** [Microsoft/ConcordExtensibilitySamples#20]
One thing that seems to be lost when using the concord api (and can also be seen in the iris sample by adding this to the entry point (just to trigger one): 
```
movesMade := 0;
movesMade := movesMade / movesMade;
```

is the lack of "view details" when having an exception:
![image](https://cloud.githubusercontent.com/assets/238568/12957867/268fdeac-d02f-11e5-8df4-3f8d3ec7e08f.png)

When using the C# debugger there's an extra "View Details"

(and I think the locals don't show the exception info either)

**Comment by gregg-miskelly** [comment]
From what I recall - the exception assistant dialog doesn't have an extensibility story. From my recollection it checks if the language is C# and if so sends down some C# expressions, or if VB sends down some VB expressions. But the design of is honestly not what we would do (it was built by another team).

For Visual Studio vNext we are working on replacing the exception assistant. So if there are particular things you would like to see (other than not hard coding expressions :)), let us know.

**Comment by carlokok** [comment]
Ah! that would explain that part! Is there a way to get the current exception though so that locals shows $Exception (or equivalent)?

**Comment by gregg-miskelly** [comment]
Yes. @pnelsonmsft what is the recommended way of supporting $exception?

**Comment by pnelsonmsft** [comment]
I created a new documentation page [here](https://github.com/Microsoft/ConcordExtensibilitySamples/wiki/CLR-Expression-Evaluator-Intrinsics).  There's a TODO in the Iris sample for this, but it will require a bunch of changes to the compiler so it can handle "unsupported" types like System.Exception.  Maybe on some long weekend I'll have time to add this to the Iris sample - unless someone beats me to it :-)

**Comment by carlokok** [comment]
Thanks! this helps a lot!

**Comment by pnelsonmsft** [comment]
The original issue is about the Exception Assistant.  The Exception Assistant is part of the debugger UI and not the debug engine so I'm closing this issue.

We are working on replacing the Exception Assistant experience.  If you have suggestions for improving it, don't hesitate to send them to us. :-)
