### ISSUE TITLE
Changes to the NuGet distribution of System.Reflection.Metadata

### ISSUE THREAD

**Issue by zargoen** [Microsoft/ConcordExtensibilitySamples#21]
I might be missing something completely obvious here but it seem that the version of System.Reflection.Metadata referenced by the Iris Example is unavailable in the listed source.
When reverting to NuGet.org it isn't available either which makes restoration difficult.

After removing it and installing it again it seem that in the current distribution available in that way the whole System.Reflection.Metadata.Decoding is Internal, the latest working version I could find was 1.1.0-alpha-00015

**Comment by plnelson** [comment]
Should be fixed now.  Let me know if you still have problems building it.
