### ISSUE TITLE
Register source language enumerator value

### ISSUE THREAD

**Issue by rainers** [Microsoft/ConcordExtensibilitySamples#28]
Hi,

I'm not sure this is the right place to ask, but is it possible to "register" a source language identifier to get listed in CV_CFL_LANG here https://github.com/Microsoft/microsoft-pdb/blob/master/include/cvconst.h#L300 ?

I have extracted the D language expression evaluator of the mago debug engine (https://github.com/rainers/mago/tree/master/EED/MagoNatCC) as a Concord extension and used 'D' (0x44) as the source language identifier for the S_COMPILE CodeView record emitted by the compiler. The installer adds appropriate "CodeView Compiler" registry entries for the VS debugger to map this identifier to the D Concord extension. Long term, this might cause conflicts with other languages using the same enumerator value, though.

LLVM got support for the S_COMPILE3 record recently, and I'd like the 'D' identifier to be added there, too. It might be easier to get addition of the appropriate translation with some "official blessing" of the actual value.

Thanks.

**Comment by gregg-miskelly** [comment]
@VCZYK is there a way that @rainers can request one of the enum CV_CFL_LANG enum values?

**Comment by rainers** [comment]
@gregg-miskelly Thanks for trying to push this forward, but it seems @VCZYK isn't very active on github. 
Maybe https://github.com/Microsoft/microsoft-pdb is a more direct place to ask for this addition...

**Comment by plnelson** [comment]
We don't own cvconst.h.  It's technically part of DIA and owned by the C++ compiler team.  @VCZYK is the owner of that file.  Because there is already an issue open in [microsoft-pdb](https://github.com/Microsoft/microsoft-pdb) I'm going to close this issue.
