### ISSUE TITLE
Problem handling exceptions with the C# HelloWorld sample

### ISSUE THREAD

**Issue by smourier** [microsoft/ConcordExtensibilitySamples#33]
Hi,

I tried to run the HelloWorld C# sample. When I debug a program, everything works fine, I can see the [HelloWorld] frame, but whenever my program hits an exception, I get the exception assistant (if enabled, otherwise I get the standard exception system) twice (one with the exception as "thrown", one for the exception as "unhandled"), but when I press F5 on the second, the program does not terminate, it like stays there and go on, hit the exception again (thrown+unhandled), and again, and again indefinitely. I can stop debugging without problem, but the behavior is clearly not the same as usual.

Is this normal? Am i supposed to do something like terminate the process/instance/thread using the API?

**Comment by plnelson** [comment]
Cleaning up old issues ... this is normal debugger behavior and unrelated to the samples.  The debugger doesn't allow continuing an unhandled exception - doing so would terminate the process.
