### ISSUE TITLE
Missing contract name on launch settings

### ISSUE THREAD

**Issue by josesimoes** [Microsoft/ConcordExtensibilitySamples#38]
Hi,

I'm trying to replicate the Iris sample on my VS extension. After hitting the Start button for debug I'm getting this error:

![2017-09-11_15-51-17](https://user-images.githubusercontent.com/1881520/30289571-7f8f63b6-9724-11e7-8d0b-45541c47a44b.png)

Any hints on what is this? 
Thanks!

**Comment by plnelson** [comment]
This is unrelated to the sample and to the debugger in general.  I'm not very familiar with the Project System, but I would try looking at the error list mentioned in the message.  If you're not able to figure it out from the error list, try asking your question on [gitter/extendvs](https://gitter.im/Microsoft/extendvs)
