### ISSUE TITLE
GetExpression

### ISSUE THREAD

**Issue by peter----** [microsoft/ConcordExtensibilitySamples#39]
Is there an way we can use it like dte2.Debugger.GetExpression?

For example, I'd like to get the return string of "objA.FunctionReturnString(3)".
How to use Concord to do it instead of use dte2.Debugger.GetExpression("objA.FunctionReturnString(3)")?

Thanks!

**Comment by plnelson** [comment]
Cleaning up old issues ... this question is unrelated to the samples.  The simple answer is to use the DTE instead of trying to call into Concord directly to evaluate something.
