### ISSUE TITLE
E_XAPI_COMPONENT_DLL_NOT_FOUND when using load symbols in external process

### ISSUE THREAD

**Issue by brunov28** [microsoft/ConcordExtensibilitySamples#48]
I have a small debugger extension that is written using IDkmCustomVisualizer API to extend some native (C++) watch variable.  The extension works as expected when load symbols in external process is not check but fails when it is.

Extension is installed by copying the .dll and .vsdconfig in the diectory desribed by the documentation https://github.com/Microsoft/ConcordExtensibilitySamples/wiki/Installing-Concord-Extensions.  So everything is copied to that folder C:\Program Files (x86)\Microsoft Visual Studio\2019\Professional\Common7\Packages\Debugger and the .natvis here C:\Program Files (x86)\Microsoft Visual Studio\2019\Professional\Common7\Packages\Debugger\Visualizers.

Is there a way to find out what is going on ?

Thanks.

**Comment by gregg-miskelly** [comment]
I added more clarification to the documentation in https://github.com/microsoft/ConcordExtensibilitySamples/wiki/Installing-Concord-Extensions. You need to switch to installing via option 1.

**Comment by brunov28** [comment]
I made the switch to option 1 and it worked.  

Thanks for the help.
