### ISSUE TITLE
visx project fails to load

### ISSUE THREAD

**Issue by Ma-XX-oN** [microsoft/ConcordExtensibilitySamples#56]
![image](https://user-images.githubusercontent.com/10625935/79536181-698e6c00-804d-11ea-8d5b-474962bd84d6.png)
I've made sure that:
1. Build is set to x86.  BTW, why is this necessary, it's not explained.
2.  'Allow NuGet to download missing packages during build.' from Tools -> Options -> NuGet Package Manager, is checked.
3. There is no file named ConcordExtensibilitySamples\CppCustomVisualizer\vsix\vsix.vcxproj.user.
4. I've also attempted to do what you say in your [If Debug Launch doesn't start Visual Studio correctly](https://github.com/Microsoft/ConcordExtensibilitySamples/wiki/Cpp-Custom-Visualizer-Sample#if-debug-launch-doesnt-start-visual-studio-correctly) Troubleshooting step manually to the visx.vcxproj to no avail.  

I'm using VS Pro 2019 v16.3.7 with .NET framework 4.8.03752.

**Comment by plnelson** [comment]
Looks like you don't have [Visual Studio Extension Development workload](https://docs.microsoft.com/en-us/visualstudio/extensibility/installing-the-visual-studio-sdk) installed.  I added a step to the wiki pages to make sure this workload is installed.

If something else is going on, the reason the project fails to load should show up in the Output window (you might need to change the "Show output from:" selection and/or try reloading).
