### ISSUE TITLE
HelloWorld Cs sample no longer converts vsdconfigxml to vsdconfig in VS 2019 Community

### ISSUE THREAD

**Issue by WheretIB** [microsoft/ConcordExtensibilitySamples#58]
MSBuild target to convert vsdconfigxml file is no longer triggered in latest Visual Studio, producing an invalid extension without vsdconfig file.

**Comment by gregg-miskelly** [comment]
I am wondering if this is just fall out from the other issue you opened. Lets try to understand that one first.

**Comment by WheretIB** [comment]
Resolved by enabling 'Automatically check for missing packages during build' option in NuGet settings.
Sorry for the trouble.
