### ISSUE TITLE
CppCustomVisualizer doesn't work when building x64 config (following instructions)

### ISSUE THREAD

**Issue by akbyrd** [microsoft/ConcordExtensibilitySamples#71]
Step 3 [here](https://github.com/Microsoft/ConcordExtensibilitySamples/wiki/Cpp-Custom-Visualizer-Sample#running-the-sample-in-visual-studio) says to build Debug x64. However, this does not appear to work. Building Debug x86 does work as expected. Might just be a typo in the instructions since the Build-x64.targets file implies the solution is expected to build in x86.

When I build and launch Debug x64 it _appears_ to work, but there's no custom visualization and I can't put breakpoints in CppCustomVisualizer code.
![image](https://user-images.githubusercontent.com/484784/147392626-3ce11522-ec2d-4174-9e28-3496da063b22.png)

Presumably this is because the vsix is not set to build in this configuration. If I attempt to build the vsix project explicitly I get an error because it's trying to copy x86 output that doesn't exist.

> Error	VSSDK1025	Could not add the file 'D:\Dev\ConcordExtensibilitySamples\CppCustomVisualizer\Debug\x86\CppCustomVisualizer.vsdconfig' to the zip package 'D:\Dev\ConcordExtensibilitySamples\CppCustomVisualizer\Debug\CppCustomVisualizer.vsix'. Could not find a part of the path 'D:\Dev\ConcordExtensibilitySamples\CppCustomVisualizer\Debug\x86\CppCustomVisualizer.vsdconfig'.	vsix	D:\Dev\ConcordExtensibilitySamples\CppCustomVisualizer\vsix\VSSDK	1

![image](https://user-images.githubusercontent.com/484784/147392721-90c5f127-9f90-4548-bf31-7cdf4f1b3006.png)

Commit 1e5dec7376ab2286e7e5742f625d77199b444812 (since I'm using 2019 and not 2022)
Windows 21H2 19044.1415
Microsoft Visual Studio Community 2019 Version 16.11.8
Visual Studio extension development workload is installed
Microsoft Child Process Debugging Power Tool is installed

**Comment by gregg-miskelly** [comment]
These instructions are for 2022. If you are targeting 2019 you will want to use the `VS16` branch, and you will want to look at the older version of various wiki pages.
