### ISSUE TITLE
Intermediate window and expression compiler

### ISSUE THREAD

**Issue by RobertvanderHulst** [microsoft/ConcordExtensibilitySamples#76]
For a custom language, how does the intermediate window decide which expression compiler to use ?

**Comment by gregg-miskelly** [comment]
All expression evaluations (Watch/Data tips/immediate window/etc) have the same algorithm -- it will look at the language of the frame in the PDB.

**Comment by RobertvanderHulst** [comment]
So when the top frame is our custom language then our expression evaluator is used. Thanks for the info.
Do you have a link to documentation about this?

**Comment by gregg-miskelly** [comment]
To be clear - not the top frame be rather the current frame.

I am not sure if there was a note somewhere else in the docs, but it seemed like something that should be called out on https://github.com/microsoft/ConcordExtensibilitySamples/wiki/Expression-Evaluators-Overview, so I added a sentence to it.
