### ISSUE TITLE
Unable to use IrisExtension following the wiki

### ISSUE THREAD

**Issue by abonie** [microsoft/ConcordExtensibilitySamples#97]
When setting IrisExtension as the startup project and hitting F5, I am getting a dialog box saying "A project with an Output Type of Class Library cannot be started directly"
<img width="302" alt="image" src="https://github.com/microsoft/ConcordExtensibilitySamples/assets/20281641/6ea1c121-2406-4a3f-bb80-c3fdd8355341">

Anything obvious I might be missing? I am trying to follow instructions from this wiki page: https://github.com/Microsoft/ConcordExtensibilitySamples/wiki/Managed-Expression-Evaluator-Sample#running-the-sample

**Comment by gregg-miskelly** [comment]
Correct

**Comment by gregg-miskelly** [comment]
I fixed the instructions in the wiki. Thanks for reporting this!
